### ISSUE TITLE
Error connection refused al intentar rastrear cualquier página

### ISSUE THREAD

**Issue by dmorenobl** [ctt-gob-es/oaw#45]
Hola,

He configurado la herramienta OAW en un servidor AlmaLinux. 

He ido siguiendo los pasos del manual y del README de Github parece todo bien configurado, pero una vez me dirijo a la página diagnostico.html del proyecto, introduzco un correo electrónico y cualquier URL y configuración, y se produce un error de 'Connection Refused'. Adjunto el log a continuación:
`2024-01-17 15:56:14,279 ERROR [es.inteco.rastreador2.utils.basic.service.BasicServiceUtils] - getBasicServiceForm BasicServiceForm [id=0, inDirectory=true, registerAnalysis=false, analysisToDelete=, analysisType=URL, complexity=0, ]
2024-01-17 15:56:14,328 ERROR [es.inteco.utils.CrawlerUtils] - Conectando con la URL: http://localhost:8080/oaw/basicServiceAction.do
2024-01-17 15:56:14,328 ERROR [es.inteco.utils.CrawlerUtils] - Conectando con la URL: http://localhost:8080/oaw/basicServiceAction.do
2024-01-17 15:56:14,329 ERROR [es.inteco.rastreador2.utils.basic.service.BasicServiceThread] - URL EXECUTE url=https%3A%2F%2Fwww.************.com%2F&correo=*******&profundidad=null&amplitud=null&informe=observatorio-4-nobroken&usuario=null&action=execute&id=66&content=&inDirectory=true
2024-01-17 15:56:14,330 ERROR [es.inteco.rastreador2.utils.basic.service.BasicServiceUtils] - getBasicServiceForm BasicServiceForm [id=66, profundidad=null, amplitud=null, inDirectory=true, registerAnalysis=false, analysisType=URL, ]
2024-01-17 15:56:14,404 ERROR [es.inteco.utils.CrawlerUtils] - Conectando con la URL: https://www.***********.com/
2024-01-17 15:56:14,625 ERROR [es.inteco.utils.CrawlerUtils] - Conectando con la URL: https://www.***********.com/
2024-01-17 15:56:14,773 ERROR [es.inteco.utils.CrawlerUtils] - Conectando con la URL: https://www.***********.com/ - Aplicando proxy: 127.0.0.1:18088
2024-01-17 15:56:14,773 INFO [es.inteco.crawler.job.CrawlerJob] - Error al rastrear el dominio https://www.***********.com/: Connection refused (Connection refused)
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.Socket.connect(Socket.java:607)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient$1.run(HttpClient.java:515)
        at sun.net.www.http.HttpClient$1.run(HttpClient.java:513)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:512)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:553)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1207)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1572)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at es.inteco.utils.CrawlerUtils.getMarkableInputStream(CrawlerUtils.java:429)
        at es.inteco.crawler.job.CrawlerJob.makeCrawl(CrawlerJob.java:459)
        at es.inteco.crawler.job.CrawlerJob.testCrawler(CrawlerJob.java:1245)
        at es.gob.oaw.basicservice.BasicServiceCrawlingManager.getCrawledLinks(BasicServiceCrawlingManager.java:61)`

He revisado varias configuraciones que existen en la ruta del proyecto y no he conseguido solucionarlo, de la misma manera he incluido en el mismo Tomcat un archivo .jsp con un ejemplo sencillo de uso de la libreria 'java.net.HttpURLConnection' (la que parece que produce el error) y ese ejemplo si me obtiene el HTML de la misma página sin problemas.

¿Alguna idea de como puedo solucionarlo?

Gracias

**Comment by dmorenobl** [comment]
He podido configurar la herramienta para realizar el rastreo mediante el panel de configuración añadiendo como semillas las páginas, asi que realmente no me hace falta revisar este caso.

Gracias

**Comment by juancaleroaltia** [comment]
Hola 

tengo el mismo error, he vuelto a hacer una instalación limpia y no consigo que registre las peticiones de diagnóstico simples. He probado a configurar semillas, etc y no hay problema con la aplicación. Parece que no hace los inserts en BD cuando se hace desde la página de diagnóstico

¿Alguna idea?

Gracias
